# Generated by Django 4.0.2 on 2022-02-10 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('endpoint', '0002_skill_eoi_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Knowledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='eoi',
            name='career_brief',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='eoi',
            name='chanllenges',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='eoi',
            name='github_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eoi',
            name='join_network',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='eoi',
            name='projects_details',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='eoi',
            name='tnc',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='eoi',
            name='knowledge',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='endpoint.knowledge'),
            preserve_default=False,
        ),
    ]
