# Generated by Django 4.0.2 on 2022-02-16 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoint', '0003_knowledge_eoi_career_brief_eoi_chanllenges_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eoi',
            name='fullname',
            field=models.CharField(default='Enter your full name', max_length=255),
        ),
    ]
