# Generated by Django 4.0.2 on 2022-02-17 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoint', '0004_eoi_fullname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eoi',
            old_name='chanllenges',
            new_name='challenges',
        ),
        migrations.AlterField(
            model_name='eoi',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('Other', 'Other')], max_length=10),
        ),
        migrations.DeleteModel(
            name='Gender',
        ),
    ]
