# Generated by Django 4.0.2 on 2022-02-17 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoint', '0005_rename_chanllenges_eoi_challenges_alter_eoi_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eoi',
            name='education',
            field=models.CharField(choices=[('SSCE', 'SSCE'), ('F', 'OND'), ('HND', 'HND'), ('BSc', 'BSc'), ('Undergraduate', 'Undergraduate')], max_length=255),
        ),
        migrations.DeleteModel(
            name='Education',
        ),
    ]
