# Generated by Django 4.0.2 on 2022-02-18 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoint', '0006_alter_eoi_education_delete_education'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eoi',
            name='education',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='eoi',
            name='gender',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='eoi',
            name='knowledge',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='eoi',
            name='skill',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Knowledge',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
